### ISSUE TITLE
Detect JVM installed

### ISSUE THREAD

**Issue by jabrena** [JDKMissionControl/jmc#8]
Hi,

I am testing latest JMC EA build 103 in OSX:
https://builds.shipilev.net/jmc/

executing the application, I receive the following error message:

```
A Java Runtime Environment (JRE) or Java Development Kit (JDK) must be available in order to run Jmc.
No Java virtual machine was found after searching the following locations:
../jdk/Contents/Home/bin
```

In the computer, I am using SDK to manage multiple JDK:

```
which java
/Users/jabrena/.sdkman/candidates/java/current/bin/java
```

and configured `JAVA_HOME` with the following value:

```
echo $JAVA_HOME
/Users/jabrena/.sdkman/candidates/java/current/
```

How to solve the issue?

Many thanks in advance

Juan Antonio

**Comment by thegreystone** [comment]
A simple workaround is to start it with the -vm flag (as per the readme). A more persistent solution is to edit the jmc.ini and add a -vm section, just like you would to the eclipse.ini.

Normally JMC EAs were built using an embedded JDK. We should probably no longer assume that this is the standard behaviour and just use the java we find on the path.

**Comment by klaraward** [comment]
You can also try removing the "-vm" line and the 
"../jdk/Contents/Home/bin" line from the jmc.ini,
then it should use whatever java you have on the path.

// Klara

**Comment by thegreystone** [comment]
Since https://bugs.openjdk.java.net/browse/JMC-6470, JMC will now use whatever JVM is on the path by default. I'm closing this issue.

**Comment by jabrena** [comment]
Upgrading the `-vm` with the path for sdkman, I could run jmc.

Many thanks for the support.

Cheers
